environment:

   matrix:

      - PYTHON_VERSION: 3.5
        MINICONDA: C:\Miniconda3-x64
        MINGWDIR: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64

init:
   - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
    - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
    - "set PATH=%MINGWDIR%;%MINGWDIR%\\bin;%PATH%"
    - "set C_INCLUDE_PATH=%MINGWDIR%\\include;%MINGWDIR%\\lib\\gcc\\x86_64-w64-mingw32\\6.3.0\\include"
    #- "cd C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64"
    #- "dir"
    #- "cd include"
    #- "dir"
    #- "cd .."
    #- "cd lib"
    #- "dir"
    - "conda config --set always_yes yes --set changeps1 no"
    - "conda update -q conda"
    - "conda info -a"
    - "conda install numpy"
    - "conda install scipy"
    - "conda install pandas"
    - "conda install matplotlib"
    - "conda install h5py"
    - "conda install setuptools"
    - "conda install sphinx"
    - "conda install sphinx_rtd_theme"
    - "conda install numpydoc"
    - "conda install nose"
    - "cd AppVeyor"
    - "copy /Y distutils.cfg %MINICONDA%\\Lib\\distutils\\distutils.cfg"
    - "copy /Y cygwinccompiler.py %MINICONDA%\\Lib\\distutils\\cygwinccompiler.py"
    - "copy /Y mingw32ccompiler.py %MINICONDA%\\Lib\\site-packages\\numpy\\distutils\\mingw32ccompiler.py"
    - "cd .."
    - "python setup.py develop"

build: off

test_script:
  - "build.cmd nosetests"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

#on_success:
