environment:

   matrix:

      - PYTHON_VERSION: 3.5
        MINICONDA: C:\Miniconda3-x64

init:
   - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
    - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
    - "conda config --set always_yes yes --set changeps1 no"
    - "conda update -q conda"
    - "conda info -a"
    - "conda install numpy"
    - "conda install scipy"
    - "conda install pandas"
    - "conda install matplotlib"
    - "conda install h5py"
    - "conda install setuptools"
    - "conda install sphinx"
    - "conda install sphinx_rtd_theme"
    - "conda install numpydoc"
    - "conda install nose"
    - "python setup.py develop"

build: off

test_script:
  - "build.cmd nosetests"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
