environment:

   matrix:

      - PYTHON: "C:\\PYTHON35-x64"


install:
    - "set PATH=C:\Miniconda3-x64;C:\Miniconda3\Scripts;%PATH%"
    - "conda install numpy"
    - "conda install scipy"
    - "conda install pandas"
    - "conda install matplotlib"
    - "conda install h5py"
    - "conda install setuptools"
    - "conda install sphinx"
    - "conda install sphinx_rtd_theme"
    - "conda install numpydoc"
    - "conda install nose"
    - "python setup.py develop"

build: off

test_script:
  - "build.cmd nosetests"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
