language: python

python:
   - "3.5"
   - "3.6"
   # - "nightly"

# safelist
branches:
   only:
      - master
      - /^release-.*$/

# 1. Step:
before_install:
  - "sudo apt-get install gfortran"
  - "sudo apt-get install libhdf5-serial-dev"
  - "pip install numpy"
  - "pip install scipy"
  - "pip install pandas"
  - "pip install matplotlib"
  - "pip install h5py"
  - "pip install setuptools"
  - "pip install sphinx"
  - "pip install sphinx_rtd_theme"
  - "pip install numpydoc"
  - "pip install nose"

# 2. Step:
install: "python3 setup.py develop"

# 3. Step:
# before_script:
# nothing

script:
  # unittests
   - "nosetests"
  # physical tests
  # - "cd tests"
  # - "python3 run_mechanical_system.py"
  # - "python3 run_mesh.py"
  # - "cd .."
  # doctest
   - "cd docs"
   - "make html"
   - "cd .."
  # build:
   - "python3 setup.py sdist"
   - "python3 setup.py bdist_wheel"

# after_sucess:
  # deploy on github

# after_failure:
  # nothing

# NO DEPLOYMENT BEACAUSE TRAVIS ONLY ALLOWS DEPLOYMENT ON CERTAIN PROVIDERS
# before_deploy:
  # nothing

#deploy:
  # nothing
  #provider: releases
  #api_key:
  #file:
  #skip_cleanup: true
  #on:
  #  tags: true

#after_deploy:
  # nothing

# after_script:
  #nothing
